### ISSUE TITLE
[Bug] marked로 해석된 마크다운 css문제

### ISSUE THREAD

**Issue by memocodee** [memocode-dev/memocode_front#32]
### ✨ 버그 리스트
---

- [ ] `- ` 사용 시에 `﹒` 가 나와야하는데 나오지 않는 문제
- [ ] `1. ` 사용 시에 `1. ` 가 나와야하는데 나오지 않는 문제

### ✏ 설명
---

테일윈드 초기화로 인해 ul, li, ol의 기본속성이 사라지는 문제가 발생했음
```css
/* 순서 없는 리스트의 스타일 복원 */
.markdown-body ul {
  list-style-type: disc; /* 또는 'circle', 'square' 등 원하는 스타일 */
  padding-left: 1em; /* 리스트 마커를 위한 왼쪽 패딩 추가 */
}

/* 순서 있는 리스트의 스타일 복원 */
.markdown-body ol {
  list-style-type: decimal; /* 숫자 마커 */
  padding-left: 1em; /* 리스트 마커를 위한 왼쪽 패딩 추가 */
}

/* 리스트 아이템 간 간격 조정 (선택 사항) */
.markdown-body li + li {
  margin-top: 0.25em;
}
```

이 css 설정을 통해 다시 원복함
